// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR0TO5jJYog2TFfO886NeulBjGslByBZE',
    appId: '1:608435301949:web:f94fd938f7ba3538dd4454',
    messagingSenderId: '608435301949',
    projectId: 'localgigfinder',
    authDomain: 'localgigfinder.firebaseapp.com',
    storageBucket: 'localgigfinder.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCk53B51YDs-VfpFaHwKzDlTNdPc4CYbE',
    appId: '1:608435301949:android:0e5375a5842454c2dd4454',
    messagingSenderId: '608435301949',
    projectId: 'localgigfinder',
    storageBucket: 'localgigfinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU3dUEMyGk3nRRht7E7_Ufi31Y_ONOl20',
    appId: '1:608435301949:ios:7b0ec403339e0806dd4454',
    messagingSenderId: '608435301949',
    projectId: 'localgigfinder',
    storageBucket: 'localgigfinder.firebasestorage.app',
    iosBundleId: 'com.example.gigFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU3dUEMyGk3nRRht7E7_Ufi31Y_ONOl20',
    appId: '1:608435301949:ios:7b0ec403339e0806dd4454',
    messagingSenderId: '608435301949',
    projectId: 'localgigfinder',
    storageBucket: 'localgigfinder.firebasestorage.app',
    iosBundleId: 'com.example.gigFinder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR0TO5jJYog2TFfO886NeulBjGslByBZE',
    appId: '1:608435301949:web:b18b9a3dcb487496dd4454',
    messagingSenderId: '608435301949',
    projectId: 'localgigfinder',
    authDomain: 'localgigfinder.firebaseapp.com',
    storageBucket: 'localgigfinder.firebasestorage.app',
  );
}
